"""
v3 — classifier (Logistic Regression)
=====================================
Trains a precision-tuned Logistic Regression classifier on the candidate pairs
generated by v2. Uses hard negatives and entity-level train/val splitting.
"""

import sys
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

import os, re, time, pickle
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
import jellyfish

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
REPO_ROOT   = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(
                os.path.abspath(__file__)))))
STUDENT_RES = os.path.join(REPO_ROOT, "6ab10eb3b23ba_student_resource", "student_resource")
TRAIN_DIR   = os.path.join(STUDENT_RES, "dataset", "mini_train") # DEVELOP ON MINI
OUTPUT_DIR  = os.path.join(STUDENT_RES, "output")
MODELS_DIR  = os.path.join(REPO_ROOT, "models")

os.makedirs(MODELS_DIR, exist_ok=True)

# ---------------------------------------------------------------------------
# Feature Engineering Helpers
# ---------------------------------------------------------------------------
def safe_jw(s1, s2):
    if not s1 and not s2: return 1.0
    if not s1 or not s2: return 0.0
    return jellyfish.jaro_winkler_similarity(s1, s2)

def safe_lev(s1, s2):
    if not s1 and not s2: return 1.0
    if not s1 or not s2: return 0.0
    d = jellyfish.levenshtein_distance(s1, s2)
    m = max(len(s1), len(s2))
    return 1.0 - (d / m) if m > 0 else 0.0

def num_overlap(s1, s2):
    t1 = set(re.findall(r'\d+', str(s1)))
    t2 = set(re.findall(r'\d+', str(s2)))
    if not t1 and not t2: return 0.0 # neutral
    if not t1 or not t2: return 0.0
    return len(t1 & t2) / len(t1 | t2) # Jaccard

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main():
    print("=" * 60)
    print("v3 — classifier (Logistic Regression)")
    print("=" * 60)
    
    t_start = time.time()
    
    # 1. Load Data
    print("\n[1/6] Loading source data and candidate pairs...")
    s1 = pd.read_csv(os.path.join(TRAIN_DIR, "train_source1.tsv"), sep="\t", dtype=str).fillna("")
    s23 = pd.concat([
        pd.read_csv(os.path.join(TRAIN_DIR, "train_source2.tsv"), sep="\t", dtype=str).fillna(""),
        pd.read_csv(os.path.join(TRAIN_DIR, "train_source3.tsv"), sep="\t", dtype=str).fillna("")
    ], ignore_index=True)
    
    gt = pd.read_csv(os.path.join(TRAIN_DIR, "train_ground_truth.tsv"), sep="\t", dtype=str).fillna("")
    cands_file = os.path.join(OUTPUT_DIR, "candidate_pairs.tsv")
    if not os.path.exists(cands_file):
        print("❌ Error: candidate_pairs.tsv not found. Run v2_blocking.py first.")
        return
        
    cands_df = pd.read_csv(cands_file, sep="\t", dtype=str).fillna("")
    
    # 2. Build Labeled Pairs (Hard Negatives)
    print("\n[2/6] Building labeled training pairs...")
    gt_map = {}
    for _, row in gt.iterrows():
        gt_map[row["source1_entity_id"]] = set(row["matched_entity_ids"].split(",")) - {""}
        
    pairs = []
    for _, row in cands_df.iterrows():
        s1_id = row["source1_entity_id"]
        c_ids = set(row["candidate_entity_ids"].split(",")) - {""}
        true_matches = gt_map.get(s1_id, set())
        
        for cid in c_ids:
            label = 1 if cid in true_matches else 0
            pairs.append({"s1_id": s1_id, "cid": cid, "label": label})
            
    df_pairs = pd.DataFrame(pairs)
    print(f"  Generated {len(df_pairs):,} total pairs.")
    print(f"  Class balance: {df_pairs['label'].mean():.2%} positive.")
    
    # 3. Join Text Data
    print("\n[3/6] Joining text data for feature engineering...")
    s1_dict = s1.set_index("entity_id")[["business_name", "business_address", "country"]].to_dict("index")
    s23_dict = s23.set_index("entity_id")[["business_name", "business_address", "country"]].to_dict("index")
    
    # Extract string lists for fast processing
    s1_names = [str(s1_dict[i]["business_name"]).lower().strip() for i in df_pairs["s1_id"]]
    s1_addrs = [str(s1_dict[i]["business_address"]).lower().strip() for i in df_pairs["s1_id"]]
    
    c_names = [str(s23_dict[i]["business_name"]).lower().strip() for i in df_pairs["cid"]]
    c_addrs = [str(s23_dict[i]["business_address"]).lower().strip() for i in df_pairs["cid"]]
    
    # 4. Feature Engineering
    print("\n[4/6] Computing features...")
    
    # String distance features
    print("  -> Jaro-Winkler & Levenshtein...")
    df_pairs["name_jw"] = [safe_jw(n1, n2) for n1, n2 in zip(s1_names, c_names)]
    df_pairs["name_lev"] = [safe_lev(n1, n2) for n1, n2 in zip(s1_names, c_names)]
    df_pairs["addr_jw"] = [safe_jw(a1, a2) for a1, a2 in zip(s1_addrs, c_addrs)]
    df_pairs["addr_lev"] = [safe_lev(a1, a2) for a1, a2 in zip(s1_addrs, c_addrs)]
    df_pairs["num_overlap"] = [num_overlap(a1, a2) for a1, a2 in zip(s1_addrs, c_addrs)]
    
    # TF-IDF Char N-gram Features
    # Since we are NOT doing a cross-join here (only aligned pairs), we can safely use memory-heavy char n-grams!
    print("  -> TF-IDF Char N-grams...")
    vec_name = TfidfVectorizer(analyzer="char_wb", ngram_range=(2,4), max_features=50_000, sublinear_tf=True)
    vec_addr = TfidfVectorizer(analyzer="char_wb", ngram_range=(2,4), max_features=50_000, sublinear_tf=True)
    
    # Fit on all names/addrs
    all_names = list(set(s1_names + c_names))
    all_addrs = list(set(s1_addrs + c_addrs))
    vec_name.fit(all_names)
    vec_addr.fit(all_addrs)
    
    # Transform exactly the aligned columns
    s1_n_vec = vec_name.transform(s1_names)
    c_n_vec  = vec_name.transform(c_names)
    s1_a_vec = vec_addr.transform(s1_addrs)
    c_a_vec  = vec_addr.transform(c_addrs)
    
    # Fast element-wise dot product
    df_pairs["name_tfidf_cosine"] = np.array(s1_n_vec.multiply(c_n_vec).sum(axis=1)).flatten()
    df_pairs["addr_tfidf_cosine"] = np.array(s1_a_vec.multiply(c_a_vec).sum(axis=1)).flatten()
    
    # Derived features
    df_pairs["name_x_addr"] = df_pairs["name_tfidf_cosine"] * df_pairs["addr_tfidf_cosine"]
    df_pairs["lookalike_flag"] = ((df_pairs["name_jw"] > 0.90) & (df_pairs["addr_jw"] < 0.50)).astype(int)
    
    features = [
        "name_jw", "name_lev", "name_tfidf_cosine",
        "addr_jw", "addr_lev", "addr_tfidf_cosine",
        "num_overlap", "name_x_addr", "lookalike_flag"
    ]
    
    # 5. Train/Val Split (Entity-level)
    print("\n[5/6] Training Logistic Regression...")
    unique_s1 = df_pairs["s1_id"].unique()
    train_s1, val_s1 = train_test_split(unique_s1, test_size=0.2, random_state=42)
    
    train_df = df_pairs[df_pairs["s1_id"].isin(train_s1)]
    val_df   = df_pairs[df_pairs["s1_id"].isin(val_s1)]
    
    print(f"  Train pairs: {len(train_df):,}  |  Val pairs: {len(val_df):,}")
    
    X_train, y_train = train_df[features], train_df["label"]
    X_val, y_val     = val_df[features], val_df["label"]
    
    model = LogisticRegression(max_iter=1000, class_weight="balanced", random_state=42)
    model.fit(X_train, y_train)
    
    print("\n  Model Coefficients:")
    for f, coef in zip(features, model.coef_[0]):
        print(f"    {f}: {coef:.4f}")
        
    with open(os.path.join(MODELS_DIR, "v3_classifier.pkl"), "wb") as f:
        pickle.dump(model, f)
        
    # 6. Threshold Tuning & Scoring
    print("\n[6/6] Tuning threshold on Validation set (F0.5 target)...")
    val_probs = model.predict_proba(X_val)[:, 1]
    val_df = val_df.copy()
    val_df["prob"] = val_probs
    
    # Reconstruct predictions to score F0.5 exactly as the competition does
    def score_at_threshold(thresh):
        pred_matches = {}
        for _, row in val_df.iterrows():
            s1_id = row["s1_id"]
            if s1_id not in pred_matches: pred_matches[s1_id] = set()
            if row["prob"] >= thresh:
                pred_matches[s1_id].add(row["cid"])
                
        # Compute macro F0.5
        scores = []
        for s1_id in val_s1:
            gt_set = gt_map.get(s1_id, set())
            pred_set = pred_matches.get(s1_id, set())
            
            if not gt_set and not pred_set:
                scores.append(1.0); continue
                
            tp = len(gt_set & pred_set)
            p = tp / len(pred_set) if pred_set else 0.0
            r = tp / len(gt_set) if gt_set else 0.0
            
            f05 = 1.25 * p * r / (0.25 * p + r) if (p+r) > 0 else 0.0
            scores.append(f05)
            
        return sum(scores) / len(scores)
        
    thresholds = np.arange(0.1, 0.95, 0.05)
    best_t, best_f05 = 0.5, 0.0
    
    for t in thresholds:
        f05 = score_at_threshold(t)
        if f05 > best_f05:
            best_f05 = f05
            best_t = t
            
    print(f"  Best Threshold: {best_t:.2f}")
    print(f"  Best Val F0.5:  {best_f05:.4f}")
    
    # Save debug scores
    debug_path = os.path.join(REPO_ROOT, "debug_scores.tsv")
    val_df.to_csv(debug_path, sep="\t", index=False)
    print(f"  Saved detailed validation scores to {debug_path}")
    
    print(f"\n[Done] Pipeline finished in {time.time()-t_start:.1f}s")

if __name__ == "__main__":
    main()
