"""
v3 — classifier (Logistic Regression)
=====================================
Trains a precision-tuned Logistic Regression classifier on candidate pairs
generated by v2. Saves the model, both TF-IDF vectorizers, and best threshold
to disk so generate_v3_submission.py can load them without refitting.

Fixes applied (audit 2026-09-25):
  - Vectorizers (vec_name, vec_addr) now saved to models/
  - best_t threshold saved to models/v3_threshold.txt
  - Fit vectorizers on train split only (no data leakage)
  - dict lookup uses .get() to avoid KeyError on stray candidate IDs
  - Empty candidate_pairs.tsv guard
  - debug_scores.tsv moved to OUTPUT_DIR
"""

import sys
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

import os, re, time, pickle
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
import jellyfish

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
REPO_ROOT   = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(
                os.path.abspath(__file__)))))
TRAIN_DIR   = os.path.join(REPO_ROOT, "dataset", "mini_train")
OUTPUT_DIR  = os.path.join(REPO_ROOT, "output")
MODELS_DIR  = os.path.join(REPO_ROOT, "models")

os.makedirs(MODELS_DIR, exist_ok=True)
os.makedirs(OUTPUT_DIR, exist_ok=True)

# ---------------------------------------------------------------------------
# Feature Engineering Helpers
# ---------------------------------------------------------------------------
def safe_jw(s1, s2):
    if not s1 and not s2: return 1.0
    if not s1 or not s2:  return 0.0
    return jellyfish.jaro_winkler_similarity(s1, s2)

def safe_lev(s1, s2):
    """Normalised Levenshtein. Returns 0.0 if either string is empty."""
    if not s1 and not s2: return 1.0
    if not s1 or not s2:  return 0.0   # FIX: was 1.0 in inference script
    d = jellyfish.levenshtein_distance(s1, s2)
    m = max(len(s1), len(s2))
    return 1.0 - (d / m) if m > 0 else 0.0

def num_overlap(s1, s2):
    t1 = set(re.findall(r'\d+', str(s1)))
    t2 = set(re.findall(r'\d+', str(s2)))
    if not t1 and not t2: return 0.0
    if not t1 or not t2:  return 0.0
    return len(t1 & t2) / len(t1 | t2)

FEATURES = [
    "name_jw", "name_lev", "name_tfidf_cosine",
    "addr_jw", "addr_lev", "addr_tfidf_cosine",
    "num_overlap", "name_x_addr", "lookalike_flag"
]

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main():
    print("=" * 60)
    print("v3 — classifier (Logistic Regression)")
    print("=" * 60)

    t_start = time.time()

    # 1. Load Data
    print("\n[1/6] Loading source data and candidate pairs...")
    s1  = pd.read_csv(os.path.join(TRAIN_DIR, "train_source1.tsv"), sep="\t", dtype=str).fillna("")
    s23 = pd.concat([
        pd.read_csv(os.path.join(TRAIN_DIR, "train_source2.tsv"), sep="\t", dtype=str).fillna(""),
        pd.read_csv(os.path.join(TRAIN_DIR, "train_source3.tsv"), sep="\t", dtype=str).fillna(""),
    ], ignore_index=True)
    gt = pd.read_csv(os.path.join(TRAIN_DIR, "train_ground_truth.tsv"), sep="\t", dtype=str).fillna("")

    cands_file = os.path.join(OUTPUT_DIR, "candidate_pairs.tsv")
    if not os.path.exists(cands_file):
        print("ERROR: candidate_pairs.tsv not found. Run v2_blocking.py first.")
        return
    cands_df = pd.read_csv(cands_file, sep="\t", dtype=str).fillna("")

    # 2. Build Labeled Pairs (Hard Negatives)
    print("\n[2/6] Building labeled training pairs...")
    gt_map = {}
    for row in gt.itertuples(index=False):
        gt_map[row.source1_entity_id] = set(row.matched_entity_ids.split(",")) - {""}

    pairs = []
    for row in cands_df.itertuples(index=False):
        s1_id    = row.source1_entity_id
        c_ids    = set(row.candidate_entity_ids.split(",")) - {""}
        true_set = gt_map.get(s1_id, set())
        for cid in c_ids:
            pairs.append({"s1_id": s1_id, "cid": cid, "label": int(cid in true_set)})

    if not pairs:
        print("ERROR: No candidate pairs found in candidate_pairs.tsv. Exiting.")
        return

    df_pairs = pd.DataFrame(pairs)
    print(f"  Generated {len(df_pairs):,} total pairs.")
    print(f"  Class balance: {df_pairs['label'].mean():.2%} positive.")

    # 3. Entity-Level Train/Val Split BEFORE fitting vectorizers (no leakage)
    print("\n[3/6] Entity-level train/val split (80/20)...")
    unique_s1 = df_pairs["s1_id"].unique()
    train_s1, val_s1 = train_test_split(unique_s1, test_size=0.2, random_state=42)
    train_df = df_pairs[df_pairs["s1_id"].isin(set(train_s1))].copy()
    val_df   = df_pairs[df_pairs["s1_id"].isin(set(val_s1))].copy()
    print(f"  Train pairs: {len(train_df):,}  |  Val pairs: {len(val_df):,}")

    # 4. Join Text Data
    print("\n[4/6] Joining text and computing features...")
    s1_dict  = s1.set_index("entity_id")[["business_name", "business_address"]].to_dict("index")
    s23_dict = s23.set_index("entity_id")[["business_name", "business_address"]].to_dict("index")

    def get_texts(df):
        s1_names = [str(s1_dict.get(i, {}).get("business_name",  "")).lower().strip() for i in df["s1_id"]]
        s1_addrs = [str(s1_dict.get(i, {}).get("business_address","")).lower().strip() for i in df["s1_id"]]
        c_names  = [str(s23_dict.get(i, {}).get("business_name",  "")).lower().strip() for i in df["cid"]]
        c_addrs  = [str(s23_dict.get(i, {}).get("business_address","")).lower().strip() for i in df["cid"]]
        return s1_names, s1_addrs, c_names, c_addrs

    tr_s1n, tr_s1a, tr_cn, tr_ca = get_texts(train_df)
    va_s1n, va_s1a, va_cn, va_ca = get_texts(val_df)

    # FIX: Fit vectorizers on TRAIN data only (no leakage into validation)
    print("  -> Fitting TF-IDF vectorizers on TRAIN split only...")
    vec_name = TfidfVectorizer(analyzer="char_wb", ngram_range=(2,4), max_features=10_000, sublinear_tf=True)
    vec_addr = TfidfVectorizer(analyzer="char_wb", ngram_range=(2,4), max_features=10_000, sublinear_tf=True)
    vec_name.fit(list(set(tr_s1n + tr_cn)))
    vec_addr.fit(list(set(tr_s1a + tr_ca)))

    def add_features(df, s1n, s1a, cn, ca):
        print("  -> String distance features...")
        df["name_jw"]  = [safe_jw(a, b)  for a, b in zip(s1n, cn)]
        df["name_lev"] = [safe_lev(a, b) for a, b in zip(s1n, cn)]
        df["addr_jw"]  = [safe_jw(a, b)  for a, b in zip(s1a, ca)]
        df["addr_lev"] = [safe_lev(a, b) for a, b in zip(s1a, ca)]
        df["num_overlap"] = [num_overlap(a, b) for a, b in zip(s1a, ca)]

        print("  -> TF-IDF cosine features...")
        s1n_v = vec_name.transform(s1n);  cn_v  = vec_name.transform(cn)
        s1a_v = vec_addr.transform(s1a);  ca_v  = vec_addr.transform(ca)
        df["name_tfidf_cosine"] = np.array(s1n_v.multiply(cn_v).sum(axis=1)).flatten()
        df["addr_tfidf_cosine"] = np.array(s1a_v.multiply(ca_v).sum(axis=1)).flatten()

        df["name_x_addr"]    = df["name_tfidf_cosine"] * df["addr_tfidf_cosine"]
        df["lookalike_flag"] = ((df["name_jw"] > 0.90) & (df["addr_jw"] < 0.50)).astype(int)
        return df

    train_df = add_features(train_df, tr_s1n, tr_s1a, tr_cn, tr_ca)
    val_df   = add_features(val_df,   va_s1n, va_s1a, va_cn, va_ca)

    # 5. Train
    print("\n[5/6] Training Logistic Regression...")
    X_train, y_train = train_df[FEATURES], train_df["label"]
    X_val,   y_val   = val_df[FEATURES],   val_df["label"]

    model = LogisticRegression(max_iter=1000, class_weight="balanced", random_state=42)
    model.fit(X_train, y_train)

    print("\n  Model Coefficients:")
    for f, coef in zip(FEATURES, model.coef_[0]):
        print(f"    {f}: {coef:+.4f}")

    # FIX: Save model AND vectorizers AND threshold
    pickle.dump(model,    open(os.path.join(MODELS_DIR, "v3_classifier.pkl"),  "wb"))
    pickle.dump(vec_name, open(os.path.join(MODELS_DIR, "v3_vec_name.pkl"),    "wb"))
    pickle.dump(vec_addr, open(os.path.join(MODELS_DIR, "v3_vec_addr.pkl"),    "wb"))
    print("\n  Saved: v3_classifier.pkl, v3_vec_name.pkl, v3_vec_addr.pkl")

    # 6. Threshold Tuning
    print("\n[6/6] Tuning threshold on validation set (F0.5 target)...")
    val_probs = model.predict_proba(X_val)[:, 1]
    val_df    = val_df.copy()
    val_df["prob"] = val_probs

    def score_at_threshold(thresh):
        pred_matches = {}
        for row in val_df.itertuples(index=False):
            if row.s1_id not in pred_matches:
                pred_matches[row.s1_id] = set()
            if row.prob >= thresh:
                pred_matches[row.s1_id].add(row.cid)

        scores = []
        for s1_id in val_s1:
            gt_set   = gt_map.get(s1_id, set())
            pred_set = pred_matches.get(s1_id, set())
            if not gt_set and not pred_set:
                scores.append(1.0); continue
            tp = len(gt_set & pred_set)
            p  = tp / len(pred_set) if pred_set else 0.0
            r  = tp / len(gt_set)   if gt_set   else 0.0
            f05 = 1.25 * p * r / (0.25 * p + r) if (p + r) > 0 else 0.0
            scores.append(f05)
        return sum(scores) / len(scores) if scores else 0.0

    best_t, best_f05 = 0.5, 0.0
    for t in np.arange(0.10, 0.96, 0.05):
        f05 = score_at_threshold(t)
        if f05 > best_f05:
            best_f05, best_t = f05, t

    print(f"  Best Threshold: {best_t:.2f}")
    print(f"  Best Val F0.5:  {best_f05:.4f}")

    # FIX: Save the threshold so inference uses the same value
    with open(os.path.join(MODELS_DIR, "v3_threshold.txt"), "w") as f:
        f.write(str(best_t))
    print(f"  Threshold saved to models/v3_threshold.txt")

    # Save debug scores to OUTPUT_DIR (not repo root)
    debug_path = os.path.join(OUTPUT_DIR, "debug_scores.tsv")
    val_df.to_csv(debug_path, sep="\t", index=False)
    print(f"  Debug scores saved to output/debug_scores.tsv")

    print(f"\n[Done] Pipeline finished in {time.time()-t_start:.1f}s")

if __name__ == "__main__":
    main()
